# Generated by Django 4.0.3 on 2022-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('phone', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
